/* This file is autogenerated, do not edit*/
#include "fakeHumanAgent_automoc.dir/moc_qjoystick_6WIRMNWCKJOTCR.cpp"
#include "fakeHumanAgent_automoc.dir/moc_genericmonitor_F5VZEYMKPI6SVF.cpp"
#include "fakeHumanAgent_automoc.dir/moc_genericworker_GFUXL3S3XLBLZ5.cpp"
#include "fakeHumanAgent_automoc.dir/moc_specificmonito_DLSZL5TUNGGYK4.cpp"
#include "fakeHumanAgent_automoc.dir/moc_specificworker_FO64C3CW4YGLTX.cpp"
